# Lab 8 Exercises

## Processing Data with Python, Part 2

---

Getting the hard part out of the way, let's import `pandas` and get our data set up.

In [2]:
import pandas as pd

chip = pd.read_csv("chipotle.tsv", sep="\t")
chip.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [3]:
chip[chip['item_name'].str.startswith("Chips")].head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
10,5,1,Chips and Guacamole,NaN,4.45
14,7,1,Chips and Guacamole,NaN,4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39

---

#### **Exercise 1**

Display a random 10 rows from this Dataframe.

In [4]:
chip.sample(10)

,order_id,quantity,item_name,choice_description,item_price
1316,536,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
3022,1201,1,Side of Chips,NaN,1.69
53,24,1,Canned Soda,[Sprite],1.09
3710,1483,1,Steak Soft Tacos,"[Fresh Tomato Salsa, Guacamole]",11.75
705,290,1,Bottled Water,NaN,1.50
4176,1667,1,Bottled Water,NaN,1.50
761,314,1,Veggie Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Cheese]]",8.75
3299,1323,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
2003,808,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]",8.75
2693,1070,1,Chips and Guacamole,NaN,4.45

#### **Exercise 2**

Calculate the average item price "the hard way," by summing the values in the column and dividing. Just like you did in math class. (Sorry.)

In [5]:
#Make a count
count = 0

for x in range(len(chip)):
    count += float(chip.loc[x, "item_price"])
    
count = count / chip["item_price"].count()
print("Average Price: ${price:.2f}".format(price= count))

Average Price: $7.46

#### **Exercise 3**

Now, calculate the mean again, using a pandas function. This is the easy way to do the above.

In [6]:
print("Average Price: ${price:.2f}".format(price = float(chip["item_price"].mean())))

Average Price: $7.46

#### **Exercise 4**

How many unique items have people ordered? What I mean by this is how many different things are there recorded for "item names," not how many orders there are in total.

List the items and how many there are. (Hint: The functions for doing those two things differ only by one letter.)

In [7]:
print("======= ITEM LIST =======")
print("Total Unique Items:", len(chip["item_name"].unique()))
print("=========================")

for x in chip["item_name"].unique():
    print(x)

======= ITEM LIST =======
Total Unique Items: 50
=========================
Chips and Fresh Tomato Salsa
Izze
Nantucket Nectar
Chips and Tomatillo-Green Chili Salsa
Chicken Bowl
Side of Chips
Steak Burrito
Steak Soft Tacos
Chips and Guacamole
Chicken Crispy Tacos
Chicken Soft Tacos
Chicken Burrito
Canned Soda
Barbacoa Burrito
Carnitas Burrito
Carnitas Bowl
Bottled Water
Chips and Tomatillo Green Chili Salsa
Barbacoa Bowl
Chips
Chicken Salad Bowl
Steak Bowl
Barbacoa Soft Tacos
Veggie Burrito
Veggie Bowl
Steak Crispy Tacos
Chips and Tomatillo Red Chili Salsa
Barbacoa Crispy Tacos
Veggie Salad Bowl
Chips and Roasted Chili-Corn Salsa
Chips and Roasted Chili Corn Salsa
Carnitas Soft Tacos
Chicken Salad
Canned Soft Drink
Steak Salad Bowl
6 Pack Soft Drink
Chips and Tomatillo-Red Chili Salsa
Bowl
Burrito
Crispy Tacos
Carnitas Crispy Tacos
Steak Salad
Chips and Mild Fresh Tomato Salsa
Veggie Soft Tacos
Carnitas Salad Bowl
Barbacoa Salad Bowl
Salad
Veggie Crispy Tacos
Veggie Salad
Carnitas Salad

#### **Exercise 5**

Using a query mask and [Pandas string methods](https://pandas.pydata.org/pandas-docs/stable/reference/series.html#string-handling), create a new dataframe of just the times people ordered chips. Print the first five such times.

In [10]:
#First just get chips orders by creating a query mask
chip_orders = chip["item_name"].str.contains("Chips")

#Apply the mask to a subset of the dataframe
chip_orders_sdf = chip[chip_orders]

#Make a copy of the subset for separate usage
chip_orders_csdf = chip_orders_sdf.copy()

print("======= CHIP ORDERS =======")
chip_orders_csdf.head(5)

======= CHIP ORDERS =======

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
6,3,1,Side of Chips,NaN,1.69
10,5,1,Chips and Guacamole,NaN,4.45
14,7,1,Chips and Guacamole,NaN,4.45

#### **Exercise 6**

What's the average item price of our "chips and something" subset?

In [12]:
print("Average Price: ${price:.2f}".format(price = float(chip_orders_csdf["item_price"].mean())))

Average Price: $3.48

#### **Exercise 7**

In this last exercise, you'll be doing our job for us. Check out the [WPRDC website](https://data.wprdc.org/dataset). Spend a few minutes looking through the available datasets, and pick one that you think is cool.

Fill out the following information about it:

**name of the dataset**: City of Pittsburgh Steps

**link:** https://data.wprdc.org/dataset/city-steps

**Who/what submitted this data to the WPRDC?** The Department of City Works via The City of Pittsburgh

**What information do I need to interpret this data? Is there a data dictionary? Is there any important information about the dataset missing?**

   To determine the average number of steps, I would simply need to calculate the average step count from the end of the table. There is no data missing for what I want to do.
    
**Why is this data of use to people in Pittsburgh? Could it be useful to anyone else: activists, politicians, researchers, companies?**

   It is useful to those who frequently partake in the traditional art of step-aerobics and other miniscule climbing activities. With the knowledge of the average step-count in the City of Pittsburgh, they can determine whether Pittsburgh is the stair-city dream that they had been wanting. The list also provides the city division responsible for maintaining the steps should they be broken.

**Can you think of any questions you want to ask of this dataset?**

   Average stair-count in the City of Pittsburgh. Division(s) that are in charge of the most staircases. The most popular type of stair building material in Pittsburgh. Streets that have a lot of stairs. Streets that are lacking in stairs.

**Is this a good dataset, in your opinion?**

   This is an extremely good start as it provides almost all the base information outside of the date the stairs were installed which would only be useful if we were to create a timeline of stairs built for historians.